### ISSUE TITLE
Immagini Draghi Rotte

### ISSUE THREAD

**Issue by pbonato3** [pbonato3/SitoPopulon#2]
Non so voi ma le immagini dei draghi sono rottissime. Bigge hai cambiato i nomi?

**Comment by biggeb4** [comment]
ho aggiunto le stesse immagini senza sfondo e i simboli dei draghi sempre senza sfondo ma non ho cambiato nessuno dei vecchi nomi

**Comment by pbonato3** [comment]
ok, non avevo visto le immagini nuove
